登记：
  号码：1 ＃您要注册的帐号
  max_workers：1 ＃多线程中的最大工人编号
  delete_low_balance_account：true＃[仅imap ]如果余额不够的话，请重新注册帐户
  DELETE_LOW_BALANCE_ACCOUNT_THRESHOLD：50＃[仅IMAP ]重新注册帐户余额阈值
  email_server：
    名称：temp_email_server ＃应该是 temp_email_server或imap_email_server
    use_custom_address：false＃[仅imap ]在使用imap_email_server时应为true
    custom_email_address：＃[仅imap ]电子邮件地址列表
    -电子邮件1@outlook.com
    -电子邮件2@outlook.com

  temp_email_server：＃TEMP电子邮件服务器您使用
    姓名：minemininboxcom

  imap_email_server：＃IMAP设置
    imap_server：imap.qq.com
    IMAP_PORT：993
    用户名：用户名
    密码：密码

oneapi：
  已启用：false ＃将数据摄取到 oneapi服务器
  URL：：http // localhost：3000＃Oneapi服务器url
  token：your_oneapi_token＃oneapi代币，在
  Channel_url：：HTTP // Local Host：3010 ＃频道的基础网址
